In [4]:
import torch

In [6]:
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
x = torch.rand(5,3)
print(x)

tensor([[0.0124, 0.5848, 0.4198],
        [0.6059, 0.1047, 0.0256],
        [0.6739, 0.5644, 0.7188],
        [0.1633, 0.8305, 0.5709],
        [0.9997, 0.0293, 0.6012]])


In [8]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x.size()

torch.Size([2])

In [11]:
x = torch.ones(5,3)
y = torch.rand(5,3)
print(x + y)

tensor([[1.3514, 1.8032, 1.8951],
        [1.3908, 1.9158, 1.9037],
        [1.1269, 1.5754, 1.4255],
        [1.5294, 1.9299, 1.0309],
        [1.0406, 1.4118, 1.0977]])


In [14]:
x = torch.randn(4,4)
y = x.view(16)
print(x)
print(y)

tensor([[-1.2157, -1.1358, -1.2983, -0.0408],
        [ 1.0108, -0.3871,  0.4803,  0.3010],
        [ 0.8348, -0.0242, -0.2221,  1.8945],
        [-0.9142,  0.3745,  0.8283, -1.6769]])
tensor([-1.2157, -1.1358, -1.2983, -0.0408,  1.0108, -0.3871,  0.4803,  0.3010,
         0.8348, -0.0242, -0.2221,  1.8945, -0.9142,  0.3745,  0.8283, -1.6769])
